# permissions for end users to edit replicationsourcedefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replicationsourcedefinition-editor-role
rules:
- apiGroups:
  - scribe.backube
  resources:
  - replicationsourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scribe.backube
  resources:
  - replicationsourcedefinitions/status
  verbs:
  - get
